version: ""

formatter: markdown table

name: terraform-module-s3-bucket-logging

content: |-
  # Terraform-module-s3-bucket-logging

  GitHub: [fapd777/terraform-module-s3-bucket-logging](https://github.com/fapd777/terraform-module-s3-bucket-logging)

  This Terraform module creates an S3 bucket for logging in the AWS account, which can later be configured for centralized logging.

  ### This module configures a bucket with:
  - Server Side Encryption (Not KMS)
  - Requires encrypted transit

  ### Module utilization example

  Create an `s3-bucket-logging.tf` file in the Terraform root directory with the following configuration:

  ```hcl
  {{ include "examples/simple-deployment/s3-bucket-logging.tfnot" }}
  ```

  Set the `ref` parameter at the end of the source URL with the latest version of the Terraform module.

  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  ## Notes
  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
